name: RPWorldInteractions
version: 0.4.1
api-version: 1.18
main: org.s1queence.plugin.RPWorldInteractions
depend: [S1queenceLib]
commands:
  actionpanel:
    usage: /ap
    permission: op
    aliases:
      - ap
  rpworldinteractions:
    usage: /rpwi <action>
    permission: op
    aliases:
      - rpwi
