name: RPWorldInteractions
version: '${project.version}'
api-version: '1.18'
main: org.s1queence.plugin.RPWorldInteractions
depend:
  - S1queenceLib
  - GSit
commands:
  actionpanel:
    usage: /ap
    aliases:
      - ap
  rpworldinteractions:
    usage: /rpwi <action>
    aliases:
      - rpwi
  vpt:
    usage: /vpt
  view:
    usage: /view <get, set, remove> <username> <perm, temp if REMOVE or SET> <text if SET>
  rummage:
    usage: /rummage <player>
  spots:
    usage: /spots <create, change, get, delete> <spot_name> <text, radius> <text>