name: RPWorldInteractions
version: '${project.version}'
api-version: '1.18'
main: org.s1queence.plugin.RPWorldInteractions
depend: [S1queenceLib]
commands:
  actionpanel:
    usage: /ap
    permission: op
    aliases:
      - ap
  rpworldinteractions:
    usage: /rpwi <action>
    permission: op
    aliases:
      - rpwi